types:
    - idl: >
        struct coordinate2d {
            long x;
            long y;
        };

    - idl: >
        struct coordinate3d {
            float x;
            float y;
            float z;
        };

systems:
    echo: { type: echo, roundtrip: true }
    mock: { type: mock }

routes:
    mock_to_echo: { from: mock, to: echo }
    echo_to_mock: { from: echo, to: mock }

topics:
    to_echo: { type: coordinate2d, route: mock_to_echo, remap: { echo: { topic: position3, type: coordinate3d } } }
    from_echo: { type: coordinate2d, route: echo_to_mock, remap: { echo: { topic: position3, type: coordinate3d } } }

