// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file AddTwoInts.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "AddTwoInts.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

AddTwoInts_Request::AddTwoInts_Request()
{
    // m_a com.eprosima.idl.parser.typecode.PrimitiveTypeCode@29626d54
    m_a = 0;
    // m_b com.eprosima.idl.parser.typecode.PrimitiveTypeCode@34b7ac2f
    m_b = 0;

}

AddTwoInts_Request::~AddTwoInts_Request()
{


}

AddTwoInts_Request::AddTwoInts_Request(
        const AddTwoInts_Request& x)
{
    m_a = x.m_a;
    m_b = x.m_b;
}

AddTwoInts_Request::AddTwoInts_Request(
        AddTwoInts_Request&& x)
{
    m_a = x.m_a;
    m_b = x.m_b;
}

AddTwoInts_Request& AddTwoInts_Request::operator =(
        const AddTwoInts_Request& x)
{

    m_a = x.m_a;
    m_b = x.m_b;

    return *this;
}

AddTwoInts_Request& AddTwoInts_Request::operator =(
        AddTwoInts_Request&& x)
{

    m_a = x.m_a;
    m_b = x.m_b;

    return *this;
}

size_t AddTwoInts_Request::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);



    return current_alignment - initial_alignment;
}

size_t AddTwoInts_Request::getCdrSerializedSize(
        const AddTwoInts_Request& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);



    return current_alignment - initial_alignment;
}

void AddTwoInts_Request::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_a;
    scdr << m_b;

}

void AddTwoInts_Request::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_a;
    dcdr >> m_b;
}

/*!
 * @brief This function sets a value in member a
 * @param _a New value for member a
 */
void AddTwoInts_Request::a(
        int64_t _a)
{
    m_a = _a;
}

/*!
 * @brief This function returns the value of member a
 * @return Value of member a
 */
int64_t AddTwoInts_Request::a() const
{
    return m_a;
}

/*!
 * @brief This function returns a reference to member a
 * @return Reference to member a
 */
int64_t& AddTwoInts_Request::a()
{
    return m_a;
}

/*!
 * @brief This function sets a value in member b
 * @param _b New value for member b
 */
void AddTwoInts_Request::b(
        int64_t _b)
{
    m_b = _b;
}

/*!
 * @brief This function returns the value of member b
 * @return Value of member b
 */
int64_t AddTwoInts_Request::b() const
{
    return m_b;
}

/*!
 * @brief This function returns a reference to member b
 * @return Reference to member b
 */
int64_t& AddTwoInts_Request::b()
{
    return m_b;
}


size_t AddTwoInts_Request::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool AddTwoInts_Request::isKeyDefined()
{
    return false;
}

void AddTwoInts_Request::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}

AddTwoInts_Response::AddTwoInts_Response()
{
    // m_sum com.eprosima.idl.parser.typecode.PrimitiveTypeCode@64cd705f
    m_sum = 0;

}

AddTwoInts_Response::~AddTwoInts_Response()
{
}

AddTwoInts_Response::AddTwoInts_Response(
        const AddTwoInts_Response& x)
{
    m_sum = x.m_sum;
}

AddTwoInts_Response::AddTwoInts_Response(
        AddTwoInts_Response&& x)
{
    m_sum = x.m_sum;
}

AddTwoInts_Response& AddTwoInts_Response::operator =(
        const AddTwoInts_Response& x)
{

    m_sum = x.m_sum;

    return *this;
}

AddTwoInts_Response& AddTwoInts_Response::operator =(
        AddTwoInts_Response&& x)
{

    m_sum = x.m_sum;

    return *this;
}

size_t AddTwoInts_Response::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    return current_alignment - initial_alignment;
}

size_t AddTwoInts_Response::getCdrSerializedSize(
        const AddTwoInts_Response& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    return current_alignment - initial_alignment;
}

void AddTwoInts_Response::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_sum;

}

void AddTwoInts_Response::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_sum;
}

/*!
 * @brief This function sets a value in member sum
 * @param _sum New value for member sum
 */
void AddTwoInts_Response::sum(
        int64_t _sum)
{
    m_sum = _sum;
}

/*!
 * @brief This function returns the value of member sum
 * @return Value of member sum
 */
int64_t AddTwoInts_Response::sum() const
{
    return m_sum;
}

/*!
 * @brief This function returns a reference to member sum
 * @return Reference to member sum
 */
int64_t& AddTwoInts_Response::sum()
{
    return m_sum;
}


size_t AddTwoInts_Response::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool AddTwoInts_Response::isKeyDefined()
{
    return false;
}

void AddTwoInts_Response::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
     
}
