types:
    idls:
        - >
            struct Dispatch
            {
                string name;
                uint32 number;
            };

systems:
  ws_client: { type: websocket_client, host: localhost, port: 12345, cert_authorities: [certs/test_authority.ca.crt],
    authentication: {
    # { user: "soss-websocket-test" } signed with secret "soss-websocket-test"
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoic29zcy13ZWJzb2NrZXQtdGVzdCIsImlhdCI6MTU1NDc5ODg4N30.c7XzL8ytDezkXTuniNi1YEYXOpKj0_Tj2gm0BLn4c4o
  }}
  ws_server: { type: websocket_server, port: 12345, cert: certs/websocket_test.crt, key: certs/websocket_test.key,
    authentication: { policies: [{ secret: soss-websocket-test, algo: HS256 }]}
  }
  mock: { type: mock, types-from: [ ws_client, ws_server ] }

routes:
  mock_to_client: { from: mock, to: ws_client }
  client_to_mock: { from: ws_client, to: mock }

  mock_to_server: { from: mock, to: ws_server }
  server_to_mock: { from: ws_server, to: mock }

topics:

  # ----- Testing mock -> client -> server -> mock
  dispatch_into_client:
    type: "Dispatch"
    route: mock_to_client
    remap: { ws_client: { topic: "dispatch_into_client/{message.name}_{message.number}/topic" } }

  "dispatch_into_client/apple_1/topic":
    type: "Dispatch"
    route: server_to_mock

  "dispatch_into_client/banana_2/topic":
    type: "Dispatch"
    route: server_to_mock

  "dispatch_into_client/cherry_3/topic":
    type: "Dispatch"
    route: server_to_mock


  # ----- Testing mock -> server -> client -> mock
  dispatch_into_server:
    type: "Dispatch"
    route: mock_to_server
    remap: { ws_server: { topic: "dispatch_into_server/{message.name}_{message.number}" } }

  "dispatch_into_server/avocado_10":
    type: "Dispatch"
    route: client_to_mock

  "dispatch_into_server/blueberry_20":
    type: "Dispatch"
    route: client_to_mock

  "dispatch_into_server/citrus_30":
    type: "Dispatch"
    route: client_to_mock
