types:
    idls:
        - >
            struct Data_Request
            {
              string request;
            };

            struct Data_Response
            {
              string response;
            };

systems:
  ws_client: { type: websocket_client, host: localhost, port: 12345, cert_authorities: [certs/test_authority.ca.crt],
    authentication: {
    # { user: "soss-websocket-test" } signed with secret "soss-websocket-test"
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoic29zcy13ZWJzb2NrZXQtdGVzdCIsImlhdCI6MTU1NDc5ODg4N30.c7XzL8ytDezkXTuniNi1YEYXOpKj0_Tj2gm0BLn4c4o
  }}
  mock: { type: mock }

routes:
  mock_to_server: { server: ws_client, clients: mock }

services:
  client_request: { request_type: "Data_Request", reply_type: "Data_Response", route: mock_to_server }